name: Deploy MiniApp to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create deployment directory
        run: |
          mkdir -p deploy
          
      - name: Copy MiniApp files
        run: |
          # Копируем index.html
          cp miniapp/index.html deploy/index.html
          
          # Создаем папку Build и копируем ВСЕ Unity файлы
          mkdir -p deploy/Build
          cp -r unity/Build/* deploy/Build/
          
          # Проверяем что скопировалось
          ls -la deploy/
          ls -la deploy/Build/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy